// Code generated by goctl. DO NOT EDIT.
// Source: product.proto

package server

import (
	"context"

	"product-srv/internal/logic"
	"product-srv/internal/svc"
	"product-srv/product"
)

type ProductServer struct {
	svcCtx *svc.ServiceContext
	product.UnimplementedProductServer
}

func NewProductServer(svcCtx *svc.ServiceContext) *ProductServer {
	return &ProductServer{
		svcCtx: svcCtx,
	}
}

func (s *ProductServer) AddCart(ctx context.Context, in *product.AddCartReq) (*product.AddCartResp, error) {
	l := logic.NewAddCartLogic(ctx, s.svcCtx)
	return l.AddCart(in)
}

func (s *ProductServer) CartList(ctx context.Context, in *product.CartListReq) (*product.CartListResp, error) {
	l := logic.NewCartListLogic(ctx, s.svcCtx)
	return l.CartList(in)
}
