// Code generated by goctl. DO NOT EDIT.
package types

type AddCartReq struct {
	SpuId string `json:"spuId"`
	SkuId string `json:"skuId"`
	Uid   int64  `json:"uid"`
	Count int64  `json:"count"`
}

type CartListReq struct {
	Uid int64 `form:"uid"`
}

type Response struct {
	Code int64       `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}
