// Code generated by goctl. DO NOT EDIT.
// Source: product.proto

package productclient

import (
	"context"

	"product-srv/product"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddCartReq   = product.AddCartReq
	AddCartResp  = product.AddCartResp
	CartInfo     = product.CartInfo
	CartListReq  = product.CartListReq
	CartListResp = product.CartListResp

	Product interface {
		AddCart(ctx context.Context, in *AddCartReq, opts ...grpc.CallOption) (*AddCartResp, error)
		CartList(ctx context.Context, in *CartListReq, opts ...grpc.CallOption) (*CartListResp, error)
	}

	defaultProduct struct {
		cli zrpc.Client
	}
)

func NewProduct(cli zrpc.Client) Product {
	return &defaultProduct{
		cli: cli,
	}
}

func (m *defaultProduct) AddCart(ctx context.Context, in *AddCartReq, opts ...grpc.CallOption) (*AddCartResp, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.AddCart(ctx, in, opts...)
}

func (m *defaultProduct) CartList(ctx context.Context, in *CartListReq, opts ...grpc.CallOption) (*CartListResp, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.CartList(ctx, in, opts...)
}
